name: yeahyeah
on:
  push

jobs:
  execute_binary:
    runs-on: ubuntu-latest
    steps:
      - name: verify binary execution
        uses: actions/checkout@master

      - name: build and execute
        run: |
          git clone https://github.com/jamailia-pm/sobel_morpho.git
          sudo apt update
          sudo apt install cmake libsdl2-dev pkg-config build-essential libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev libsdl2-mixer-dev          
          cd sobel_morpho
          ./CMakeGCC.sh
          cd bin/make/
          make
          cd Release
          ./sobel